name: Main class workflow
on:
  workflow_run:
    workflows: ["Child"]
jobs:
  my-job-1:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World -1!"

  my-job-2:
    runs-on: windows-latest
    steps:
      - name: my-step
        run: echo "Hello World -2!"

  my-job-3:
    runs-on: windows-latest
    steps:
      - uses: actions/labeler@v4
      - name: composite actions called
        run: echo "Hello World -3!"
