name: hello-world3
run-name: ${{ github.actor }} is learning GitHub Actions
'on': push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World Test -3!"
