name: child
run-name: '${{ github.actor }} is learning GitHub Actions'
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    branch_protection_rule:
      types:
        - created
        - deleted
jobs:
  job-01:
    runs-on: ubuntu-latest
    steps:
      - name: my-step-1
        run: echo "Hello World Test -1!"
  job-02:
    runs-on: ubuntu-latest
    steps:
      - name: my-step-2
        run: echo "Hello World Test -2!"
  job-03:
    runs-on: windows-latest
    steps:
      - name: my-step-3
        run: echo "Hello World Test -3!"

